# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo_list_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from datetime import date



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 700)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 255)\n""")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        ##Line edit
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 60, 471, 41))
        self.lineEdit.setStyleSheet("color:rgb(0, 0, 127);\n"
"background-color:white;\n"
"font: 63 10pt \"Cambria\";\n"
"border-radius: 10px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("input_text")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 0, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(55)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        
        ##Title
        self.label.setStyleSheet("color:rgb(0, 47, 143);\n"
"font:bold 25pt \"Cambria \";\n"
"background-color: rgb(192, 250, 255);\n"
"border-bottom-width: 2px;\n"
"border-bottom-style: solid;\n"
"border-radius: 5px;\n""")
        self.label.setObjectName("label")
        
        ##Date label
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(610, -10, 101, 41))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(0, 0, 127);\n""font: 15pt \"Georgia\";")
        self.label_2.setObjectName("label_2")
        
        ##Date
        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(660, 0, 91, 21))
        self.date.setStyleSheet("color:rgb(0, 0, 127);\n"
"font: 12pt \" Cambria\";")
        self.date.setObjectName("date")
        
        ##Remove
        self.Remove = QtWidgets.QPushButton(self.centralwidget)
        self.Remove.setGeometry(QtCore.QRect(330, 120, 131, 41))
        self.Remove.setStyleSheet("QPushButton{""border-radius:10;\n""color:white;\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"background-color:rgb(0, 0, 127);""}"
"QPushButton:hover{""background-color : rgb(0, 0, 10);""}")
        self.Remove.setObjectName("Remove")
        
        ##ADD
        self.ADD = QtWidgets.QPushButton(self.centralwidget)
        self.ADD.setGeometry(QtCore.QRect(180, 120, 131, 41))
        self.ADD.setStyleSheet("QPushButton{""border-radius:10;\n""color:white;\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"background-color:rgb(0, 0, 127);""}"
"QPushButton:hover{""background-color : rgb(0, 0, 10);""}")
        self.ADD.setObjectName("ADD")
        
        #clear list
        self.clear_list = QtWidgets.QPushButton(self.centralwidget)
        self.clear_list.setGeometry(QtCore.QRect(480, 120, 131, 41))
        self.clear_list.setStyleSheet("QPushButton{""border-radius:10;\n""color:white;\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"background-color:rgb(0, 0, 127);""}"
"QPushButton:hover{""background-color : rgb(0, 0, 10);""}")
        self.clear_list.setObjectName("clear_list")
        
        ##List View
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(160, 200, 471, 361))
        self.listWidget.setStyleSheet("color:rgb(0, 0, 127);\n"
"background-color: rgb(198, 251, 255);\n"
"font: 63 13pt \"Cambria\";\n"
"border-radius: 10px;")
        self.listWidget.setObjectName("listView")
        

        
        ###history
        self.history = QtWidgets.QPushButton(self.centralwidget)
        self.history.setGeometry(QtCore.QRect(210, 575, 131, 41))
        self.history.setStyleSheet("QPushButton{""border-radius:10;\n""color:white;\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"background-color:rgb(0, 0, 127);""}"
"QPushButton:hover{""background-color : rgb(0, 0, 10);""}")
        self.history.setObjectName("history")
        
        ##clear_history
        self.clear_history = QtWidgets.QPushButton(self.centralwidget)
        self.clear_history.setGeometry(QtCore.QRect(450, 575, 131, 41))
        self.clear_history.setStyleSheet("QPushButton{""border-radius:10;\n""color:white;\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"background-color:rgb(0, 0, 127);""}"
"QPushButton:hover{""background-color : rgb(0, 0, 10);""}")
        self.clear_history.setObjectName("clear_history")
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ToDo list-Eswar"))
        self.label.setText(_translate("MainWindow", "        ToDo List"))
        self.label_2.setText(_translate("MainWindow", "Date :"))
        self.Remove.setText(_translate("MainWindow", "REMOVE"))
        self.ADD.setText(_translate("MainWindow", "ADD"))
        self.clear_list.setText(_translate("MainWindow", "CLEAR LIST"))
        self.history.setText(_translate("MainWindow", "HISTORY"))    
        self.clear_history.setText(_translate("MainWindow", "CLEAR HISTORY"))    
        self.date.setText(_translate("MainWindow", "27-02-2023"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
