# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_button.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.click = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it()) #Calling the function here
        self.click.setGeometry(QtCore.QRect(290, 390, 191, 61))
        self.click.setObjectName("click")
        self.eswar_label = QtWidgets.QLabel(self.centralwidget)
        self.eswar_label.setGeometry(QtCore.QRect(290, 260, 321, 121))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.eswar_label.setFont(font)
        self.eswar_label.setObjectName("eswar_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def press_it(self):
        self.eswar_label.setText("Bhoom..!")#created the function for button click


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.click.setText(_translate("MainWindow", "Click!"))
        self.eswar_label.setText(_translate("MainWindow", "Hello eswar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
