#Here we are verifying the bounding box points that are generated by the surveyboard labeling are correct or not by drawing them in image and comparing them

import pandas as pd
import cv2
import ast


df = pd.read_csv(r"E:\Coding\Python\matrix_training\task-2\Distress_Check_with_File_Path.csv")
print(df.info())
files = df["File_Path"]
boundingbox = df["BoundingBox"]
dclass = df["Distress_Class"]
count = 0
for i in files.head(30):
    image = cv2.imread(i)
    resized_img = cv2.resize(image,(1565,132))
    bounding_box1 = boundingbox[count]
    # print()
    # print(bounding_box1)
    # bb = bounding_box1.strip('][').split(', ')
    bb = ast.literal_eval(bounding_box1)
    
    x1 = int(bb[0])
    y1 = int(bb[1])
    x2 = int(bb[2])+int(bb[0])
    y2 = int(bb[3])+int(bb[1])
    if x1<0:
        x1 = 0
    if x2<0:
        x2 = 0
    if y1<0:
        y1=0
    if y2<0:
        y2=0
    print(x1,y1,x2,y2,i,dclass[count])
    start_point = x1,y1
    end_point = x2,y2
    Bbox = cv2.rectangle(resized_img, start_point, end_point, color =(255, 0, 0), thickness=2)
    
    
    # cv2.imshow("image", image)
    # cv2.waitKey(0)
    cv2.imshow("reimage", Bbox)
    cv2.waitKey(0)
    count+=1